attach(UScereal)
names(UScereal)
#The relationship between manufacturer and shelf
table(mfr, shelf)
barplot(table(mfr, shelf), beside = TRUE, legend.text = c("General Mills", "Kelloggs", "Nabisco", "Post", "Quaker Oats", "Ralston Purina"), col = c("cornflowerblue", "red", "sandybrown", "yellow1", "lemonchiffon", "firebrick3"),xlab = "Display shelf")
#The relationship between fat and vitamins
boxplot(fat ~ vitamins, horizontal = TRUE)
#The relationship between fat and shelf
boxplot(fat ~ shelf, horizontal = TRUE)
#The relationship between carbohydrates and sugars
cor(sugars, carbo)
plot(sugars, carbo)
abline(lm(carbo~sugars))
#The relationship between fibre and manufacturer
boxplot(fibre ~ mfr,names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer", ylab = "Fibre")
#The relationship between sodium and sugars
cor(sugars, sodium)
plot(sugars, sodium)
abline(lm(sodium~sugars))
#Are there other relationships you can predict and investigate?
boxplot(calories ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer")
boxplot(protein ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer")
boxplot(fat ~ mfr,names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer")
boxplot(sodium ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer")
boxplot(carbo ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"), xlab = "Manufacturer")
boxplot(sugars ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"),xlab = "Manufacturer")
boxplot(potassium ~ mfr, names = c("G. Mills", "Kelloggs", "Nabisco", "Post", "Q. Oats", "R. Purina"), xlab = "Manufacturer")
boxplot(calories ~ shelf)
boxplot(protein ~ shelf)
boxplot(sodium ~ shelf)
boxplot(fibre ~ shelf)
boxplot(carbo ~ shelf)
boxplot(sugars ~ shelf)
boxplot(potassium ~ shelf)
cor(protein, calories)
plot(protein, calories)
abline(lm(calories~protein))
cor(fat, calories)
plot(fat, calories)
abline(lm(calories~fat))
cor(sodium, calories)
plot(sodium, calories)
abline(lm(calories~sodium))
cor(fibre, calories)
plot(fibre, calories)
abline(lm(calories~fibre))
cor(carbo, calories)
plot(carbo, calories)
abline(lm(calories~carbo))
cor(sugars, calories)
plot(sugars, calories)
abline(lm(calories~sugars))
cor(potassium, calories)
plot(potassium, calories)
abline(lm(calories~potassium))