#??) X???N(5,2)
x <- rnorm(100, mean = 5, sd = sqrt(2))
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dnorm(x, mean = 5, sd = sqrt(2)), add = TRUE, col = "red")
skewness(x)
qnorm(0.995, 0, 1)
kurtosis(x)
qnorm(0.995, 0, 1)
#??) X???U(1,5)
x <- runif(100, min = 1, max = 5)
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dunif(x, min = 1, max = 5), add = TRUE, col = "red")
skewness(x)
kurtosis(x)
#??) X???Exp(3)
x <- rexp(100, rate = 3)
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dexp(x, rate = 3), add = TRUE, col = "red")
skewness(x)
kurtosis(x)
#??) X???Gamma(5,1)
x <- rgamma(100, shape = 5, rate = 1)
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dgamma(x, shape = 5, rate = 1), add = TRUE, col = "red")
skewness(x)
kurtosis(x)
#??) X?????2(3)
x <- rchisq(100, df = 3)
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dchisq(x, df = 3), add = TRUE, col = "red")
skewness(x)
kurtosis(x)
#??) X???t(5)
x <- rt(100, df = 5)
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
curve(dt(x, df = 5), add = TRUE, col = "red")
skewness(x)
kurtosis(x)
#??) X ?? ???????? ???? ?????? ?????????????????????????? N(1,2) ?? N(5,2) ?? ???????????????????? ???? ?????????????? p=0.4
i <- rbinom(100, size = 1, prob = 0.4)
n1 <- rnorm(100, mean = 1, sd = sqrt(2))
n2 <- rnorm(100, mean = 5, sd = sqrt(2))
x <- i * n1 + (1 - i) * n2
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
skewness(x)
kurtosis(x)
#??) X ?? ???????? ???? ?????? ?????????????????????????? N(1,2), N(10,2) ?? N(???3,2) ?? ?????????????????????? ?????????????????? p1=0.3, p2=0.2 ?? p3=0.5.
u <- runif(1000)
p1 <- 0.3
p2 <- 0.2
p3 <- 0.5
i1 <- u < p1
i2 <- u > p1 & u < p2+p1
i3 <- u > p1+p2
n1 <- rnorm(1000, mean = 1, sd = sqrt(2))
n2 <- rnorm(1000, mean = 10, sd = sqrt(2))
n3 <- rnorm(1000, mean = -3, sd = sqrt(2))
x <- i1 * n1 + i2 * n2 + i3 * n3
boxplot(x, horizontal = TRUE)
hist(x, probability = TRUE)
lines(density(x, bw = "SJ"), col = "blue")
skewness(x)
kurtosis(x)